version: "3"

services:
  mysql:
    image: mysql:8.0.25
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root#123
    ports:
      - "3316:3306"
    volumes:
      - D:/DockerData/CommonData/mysql:/var/lib/mysql
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - D:/DockerData/CommonData/redis:/data