basePath: /api/v1
definitions:
  model.User:
    properties:
      created_at:
        type: string
      deleted_at:
        type: string
      enable:
        type: boolean
      id:
        type: integer
      last_login:
        type: string
      name:
        type: string
      password:
        type: string
      phone:
        type: string
      plain_password:
        type: string
      roles:
        items:
          type: string
        type: array
      updated_at:
        type: string
      username:
        type: string
    type: object
host: localhost:9060
info:
  contact:
    email: support@swagger.io
    name: go-swagger帮助文档
    url: https://github.com/swaggo/swag/blob/master/README_zh-CN.md
  description: 演示说明文档
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: GinFx-Template
  version: 1.0.0
paths:
  /api/user/add:
    post:
      parameters:
      - description: User信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.User'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: 新增用户
      tags:
      - 用户管理
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
